"""Scenario data models — shared across planning, patient agent, and analysis."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from enum import Enum
from pathlib import Path
from typing import Any

import yaml
from pydantic import BaseModel, Field, field_validator


class ScenarioCategory(str, Enum):
    """Allowed test categories for orchestrator and generator."""

    SCHEDULING = "scheduling"
    RESCHEDULE = "reschedule"
    CANCEL = "cancel"
    REFILL = "refill"
    INSURANCE = "insurance"
    HOURS_LOCATION = "hours_location"
    EDGE_CASE = "edge_case"
    INTERRUPTION = "interruption"
    AMBIGUOUS_REQUEST = "ambiguous_request"


class PatientProfile(BaseModel):
    """Fake patient identity used when the agent asks intake questions."""

    name: str
    dob: str = Field(description="Date of birth, e.g. MM/DD/YYYY")
    phone: str = Field(description="Fake US phone number")
    insurance: str


class Scenario(BaseModel):
    """A complete test scenario — generated by LLM or loaded from a seed file."""

    id: str
    category: ScenarioCategory
    name: str
    description: str
    patient: PatientProfile
    goal: str
    behavior: list[str] = Field(min_length=1)
    success_criteria: list[str] = Field(min_length=1)
    tags: list[str] = Field(default_factory=list)
    generated_at: datetime | None = None
    orchestrator_hint: str | None = None
    source: str = Field(default="generated", description="generated | seed")

    @field_validator("goal")
    @classmethod
    def goal_not_empty(cls, value: str) -> str:
        if not value.strip():
            raise ValueError("goal must not be empty")
        return value.strip()

    def to_patient_prompt_context(self) -> dict[str, Any]:
        """Fields safe to inject into the Realtime patient system prompt."""
        return {
            "patient": self.patient.model_dump(),
            "goal": self.goal,
            "behavior": self.behavior,
        }

    def save(self, path: Path) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            json.dumps(self.model_dump(mode="json"), indent=2),
            encoding="utf-8",
        )

    @classmethod
    def load(cls, path: Path) -> Scenario:
        data = json.loads(path.read_text(encoding="utf-8"))
        return cls.model_validate(data)


class OrchestratorPlan(BaseModel):
    """Orchestrator output — what type of test to run next."""

    next_category: ScenarioCategory
    hint: str
    avoid: list[str] = Field(default_factory=list)
    rationale: str


class CallStatus(str, Enum):
    """Lifecycle of a planned or completed call."""

    GENERATED = "generated"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"


class CallHistoryEntry(BaseModel):
    """One row in outputs/call_history.json."""

    call_id: str
    scenario_id: str
    category: ScenarioCategory
    status: CallStatus
    scenario_path: str
    created_at: datetime
    completed_at: datetime | None = None
    bug_count: int | None = None
    notes: str | None = None


class CallHistory(BaseModel):
    """Persistent record of all generated scenarios and completed calls."""

    entries: list[CallHistoryEntry] = Field(default_factory=list)

    def categories_used(self) -> list[str]:
        return [entry.category.value for entry in self.entries]

    def recent_avoid_tags(self, limit: int = 8) -> list[str]:
        return self.categories_used()[-limit:]

    def add(self, entry: CallHistoryEntry) -> None:
        self.entries.append(entry)


def next_call_id(output_dir: Path) -> str:
    """Allocate the next call-NN id from per-call folders (and legacy flat scenarios)."""
    numbers: list[int] = []
    for folder in output_dir.glob("call[0-9][0-9]"):
        if folder.is_dir():
            part = folder.name[4:]
            if part.isdigit():
                numbers.append(int(part))
    legacy_scenarios = output_dir / "scenarios"
    if legacy_scenarios.is_dir():
        for path in legacy_scenarios.glob("call-*.json"):
            part = path.stem.replace("call-", "")
            if part.isdigit():
                numbers.append(int(part))
    return f"call-{max(numbers, default=0) + 1:02d}"


def load_seed_scenario(path: Path) -> Scenario:
    """Load a YAML seed scenario from scenarios/seeds/ for debug runs."""
    raw = yaml.safe_load(path.read_text(encoding="utf-8"))
    category_value = raw.get("category")
    if category_value:
        category = ScenarioCategory(category_value)
    else:
        tags = raw.get("tags") or []
        category = _infer_category_from_tags(tags)

    return Scenario(
        id=raw["id"],
        category=category,
        name=raw.get("name", raw["id"]),
        description=raw.get("description", ""),
        patient=PatientProfile.model_validate(raw["patient"]),
        goal=raw["goal"].strip() if isinstance(raw["goal"], str) else str(raw["goal"]),
        behavior=raw["behavior"],
        success_criteria=raw["success_criteria"],
        tags=raw.get("tags", []),
        source="seed",
    )


def _infer_category_from_tags(tags: list[str]) -> ScenarioCategory:
    """Best-effort category when seed YAML omits an explicit category."""
    priority = [
        "edge_case",
        "interruption",
        "ambiguous_request",
        "reschedule",
        "cancel",
        "refill",
        "insurance",
        "hours_location",
        "scheduling",
    ]
    mapping = {item: ScenarioCategory(item) for item in priority}
    for tag in priority:
        if tag in tags:
            return mapping[tag]
    return ScenarioCategory.SCHEDULING


def utc_now() -> datetime:
    return datetime.now(timezone.utc)
